INSERT INTO forms_questions (id, form_type, question, created_at, updated_at) VALUES
(10, 'pre', 'Como te sentes em relação à tua preparação para o e-fólio?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 'pre', 'Aproximadamente, quantas horas no total estimas ter dedicado à preparação para este e-fólio?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 'pre', 'As atividades formativas ajudaram-te a preparar o e-fólio?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 'pre', 'Os materiais de apoio (PDFs, vídeos, links, etc.) foram úteis para a tua preparação?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 'pre', 'Foi fácil encontrar e aceder aos recursos e atividades no Moodle?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 'pos', 'Depois de teres realizado o e-fólio, como classificas a tua preparação?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 'pos', 'Qual é a tua expectativa de desempenho neste e-fólio?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 'pos', 'Quanto tempo estimado dedicaste à realização do e-fólio (durante os dias disponíveis para o fazer)?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 'pos', 'Como classificas a dificuldade do e-fólio?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 'pos', 'Como avalias o esforço que investiste na preparação e realização deste e-fólio?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 'pos', 'Os conteúdos e materiais disponibilizados cobriram bem os temas abordados no e-fólio?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 'pos', 'Relativamente á sessão síncrona de apoio ao e-fólio, como a avalias?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO forms_answers (id, question_id, answer, created_at, updated_at) VALUES
(27, 10, 'Ainda me sinto perdido/a - Não tive tempo para estudar ou ainda não entendi bem a matéria.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 10, 'Estou a meio - Já comecei a estudar, mas ainda tenho dúvidas ou falta terminar a preparação.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 10, 'Sinto-me preparado/a - Estudei bem, percebo os conteúdos e estou confiante para realizar o e-fólio.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 11, 'Entre 10 e 20 horas (inclusive).', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 11, 'Entre 20 e 40 horas (inclusive).', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 11, 'Entre 5 e 10 horas (inclusive).', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 11, 'Mais de 40 horas.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 11, 'Menos de 5 horas.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 12, 'Efetuei, mas a correção/resolução não ajudou a perceber os erros ou a matéria.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 12, 'Efetuei, mas estavam desatualizadas ou não se relacionavam bem com o conteúdo atual.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 12, 'Foram bem construídas, claras e ajudaram bastante na minha preparação.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 12, 'Foram úteis, mas encontrei lacunas nalguns temas ou explicações mais detalhadas.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 12, 'Não efetuei ou não encontrei atividades específicas.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 13, 'Não cheguei a utilizar os materiais ou não os encontrei.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 13, 'Os materiais ajudam em alguns pontos, mas podiam estar mais organizados ou mais completos.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 13, 'Os materiais estavam bem estruturados e foram úteis para compreender os conteúdos.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 13, 'Utilizei os materiais, mas senti que eram pouco claros, desatualizados ou não ajudaram muito.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 14, 'A navegação foi simples e os conteúdos estavam bem organizados e acessíveis.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 14, 'Consegui encontrar o essencial, mas a estrutura podia ser mais clara e intuitiva.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 14, 'Tive bastante dificuldade em localizar os conteúdos – a estrutura não era clara e/ou a navegação parecia desorganizada.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 15, 'Estava preparado/a – compreendi bem os conteúdos e senti que consegui aplicar os conhecimentos com confiança.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 15, 'Estava razoavelmente preparado/a – consegui responder, mas ainda com algumas dúvidas ou inseguranças.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 15, 'Não estava devidamente preparado/a – percebi que ainda não dominava bem os conteúdos ou não tive tempo suficiente para estudar.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 16, 'Expectativa elevada – senti que correu bem e espero um resultado muito bom.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(51, 16, 'Expectativa moderada – respondi ao essencial, mas com dúvidas ou deixando partes por fazer.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 16, 'Expectativa positiva – consegui aplicar os conhecimentos e senti segurança na maioria das respostas.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(53, 16, 'Não consegui responder ou espero ter um resultado muito baixo.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(54, 17, 'Entre 2h a 5h (inclusive).', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(55, 17, 'Entre 5h a 10h (inclusive).', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(56, 17, 'Mais de 10h.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(57, 17, 'Menos de 2h.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(58, 18, 'Exigente, achei difícil, não consegui responder e/ou senti que as atividades não me prepararam adequadamente.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 18, 'Fácil, consegui aplicar o que estudei com confiança.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(60, 18, 'Moderado, consegui aplicar o que estudei, mesmo que apenas parcialmente ou com algumas dificuldades de execução.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(61, 19, 'Fiz um esforço razoável, existiram limitações profissionais/pessoais que me impediram de me focar a 100%.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(62, 19, 'Não consegui dedicar o tempo ou a atenção necessária – sinto que o meu esforço ficou aquém do desejado.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(63, 19, 'Sinto que investi tudo o que podia – estudei com dedicação, organizei-me bem e mantive o compromisso até ao fim.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(64, 20, 'Não - senti que vários tópicos abordados não estavam nos materiais.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(65, 20, 'Parcialmente - cobriram o essencial, mas senti algumas lacunas.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(66, 20, 'Sim - os materiais prepararam-me para o que foi pedido.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(67, 21, 'Foi muito útil – esclareceu dúvidas e deu boa orientação para o estudo.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(68, 21, 'Foi útil, esclareceu alguns pontos, mas deixou dúvidas importantes por esclarecer e/ou poderia ter sido mais aprofundada.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(69, 21, 'Não existiu sessão síncrona de apoio á realização do e-fólio.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(70, 21, 'Não foi útil – os temas abordados não ajudaram na preparação, foi confusa ou senti que houve falta de preparação.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);