
services:
  moodle:
    image: moodlehq/moodle-php-apache:8.1
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    environment:
      - MOODLE_DOCKER_DBTYPE=mysqli
      - MOODLE_DOCKER_DBHOST=db
      - MOODLE_DOCKER_DBNAME=moodle
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS=moodle

  uni-analytics:
    build:
      context: ./uni-analytics
    volumes:
      - ./uni-analytics:/app
      - ./uni-analytics/logs:/app/logs
    depends_on:
      - db
    environment:
    # Database Configuration
      - DB_HOST=db
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=moodle
      # Logging Configuration
      - LOG_LEVEL=DEBUG
      - LOG_RETENTION_DAYS=2
      - LOG_DIR=/app/logs
      - LOG_FILENAME=uniAnalytics.log
      - LOG_ROTATE_WHEN=midnight
      - LOG_ROTATE_INTERVAL=1
    command: ["python", "main.py"]
    ports:
      - "8050:8050"
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: